### ISSUE TITLE
How to start the project?

### ISSUE THREAD

**Issue by tabital0** [AlexandreBrg/go-clearkey-server#5]
The webpage is not showing up. Docker starts okay and looks fine but once opened up in the browser no webpage. i exposed port 8080 in docker but no luck getting it to work.

**Comment by AlexandreBrg** [comment]
This API isn't rendering any website page, only JSON content through routes `/license` or `/license/register`.

Here is the running process (I did put a docker image instead of doing `go run .`), is it something similar to what you've done ?
```
# Go into the repo folder
cd go-clearkey-server
# Run the database
docker-compose up

# This run the docker image of the project & expose port 8080 on your host machine
docker run -p 8080:8080 protocole/go-clearkey-server
```

**Comment by tabital0** [comment]
Nice. It started i like to use it as a replacement of my current server but for that ill need SSL. Is there a way to implement SSL?

Also the "/license/register" is not fully clear to me how to add a new lisence the example goes into "/license" part how to obtain the license for the webplayer (test.html) but how to add one so i can test it out? I am really lookng forward to this project. Thanks for the amazing work

**Comment by AlexandreBrg** [comment]
Based on my knowledge, TLS shouldn't be implemented at the application level, but more at infrastructure level. You can do it if you have an [nginx](https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-20-04) upfront for instance. 

`/license/register` follows [W3C format](https://www.w3.org/TR/encrypted-media/#clear-key-license-format), which is the standard format for ClearKey licensing. I'm seeing that I've put a link to section `9.1.4` instead of `9.1.3` in the readme, my mistake on this.

As you see in `9.1.3`, the server is expecting the below format. Be aware that `kids` (for `Key IDs`) must be `base64encoded`.

```json
{
  "kids":
    [
     "LwVHf8JLtPrv2GUXFW2v_A",
     "0DdtU9od-Bh5L3xbv0Xf_A"
    ],
  "type":"temporary"
}
```

I hope it helps, this conversation will certainly help me to make a better readme.
